### ISSUE TITLE
Extension point xsl.transtype-epub is not declared in plugin.xml

### ISSUE THREAD

**Issue by robertnthomas** [dita4publishers/dita4publishers#11]
org.dita4publishers.epub/plugins.xsl mentions "xsl.transtype-epub" in line 3:

&lt;extension id="xsl.transtype-epub"/>

I suspect what was meant is something like this:

&lt;extension-point id="xsl.transtype-epub" name="EPUB XSLT import"/>

**Comment by drmacro** [comment]
Fixed on dev branch. Also fixed same error in example custom EPUB plugin.
