### ISSUE TITLE
External link without format attribute still tries to read file

### ISSUE THREAD

**Issue by robander** [dita4publishers/dita4publishers#14]
I'm not sure if this is by design or not, opening just in case because the markup is fairly common even if it doesn't meet the letter of the specification.

The DITA-OT 1.8 docs had a couple of reltable links to external web pages. Both set `scope="external"` but neither set `@format`. These are very old links, one even used `type="html"` which was how we identified HTML links before DITA went to OASIS. The links have been cleaned up in the DITA-OT 2.0 docs. 

But - this type of linking is still commonly found in quite a few docs I'm familiar with. When I run it through the epub transform - and I'm not using the latest code - the `df:resolveTopicRef` function tries to read both of these as DITA topics, resulting in a long hang followed by errors about the content:
```xml
<topicref href="http://opensource.org/licenses/cpl1.0.php"
navtitle="Common Public License, version 1.0" type="html" scope="external" />
<topicref href="http://www.apache.org/licenses/LICENSE-2.0" navtitle="Apache License, version 2.0"
scope="external"/>
```

I went into the `df:resolveTopicRef` function and added a test for `scope=peer` or `scope=external` right after the current test for `@format`, and that fixed the problem - the code did not try to read the resources, did not generate errors. I think that this is proper even if the links really should set `@format`, because there are no other spots today where DITA-OT attempts to external resources - they are presumed unavailable or outside the scope of this content.

**Comment by drmacro** [comment]
Given that DITA 1.3 defines rules for inferring the format from the URI details I think this definitely needs to be handled as you described.

It's a small change, I'll see what I can do and not ask you to make a pull request unless doing so would be easy for you :-)

**Comment by robander** [comment]
I should be able to get the pull request, just hadn't forked the repository yet. Just did that and should get the update before long.

**Comment by drmacro** [comment]
Cool

**Comment by robander** [comment]
Was taking quite a long time to download all the submodules, so I've tried putting the suggested change directly in through the web client. Not sure if that counts as a pull request, but I think it can be merged if it looks good.
