### ISSUE TITLE
epub failing?

### ISSUE THREAD

**Issue by brbk** [dita4publishers/dita4publishers#17]
Hi there,

I'm trying to get the epub plugin working with OT 1.8.5. 

It's currently failing with this error,
Caused by: javax.xml.transform.TransformerException: Malformed URL plugin:org.dita4publishers.common.xslt:xsl/reportParametersBase.xsl(base file:/C:/ProgFiles/Server/publish/DITA-OT185/plugins/org.dita4publishers.epub/xsl/map2epubImpl.xsl)

Any help is appreciated.

Barb

**Comment by drmacro** [comment]
Are you using the latest 1.0.0RC14 release?

**Comment by brbk** [comment]
I downloaded the plugin last week.

**Comment by drmacro** [comment]
Can you provide the full OT log?

**Comment by brbk** [comment]
I don't have a full log file because I'm running a cmd window off the dita ot. (Other output types, like xhtml, are working when I test this way.)

From this command,
C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185>ant -Dargs.input=./samples/hierarchy.ditamap -Dtranstype=epub

I get this much of the process remaining in the cmd window,

o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\html.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\hreftargets.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\canditopics.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\skipchunk.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\subjectscheme.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\conreftargets.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\copytosource.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\subtargets.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\conrefpush.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\keyref.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\coderef.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\resourceonly.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
     [echo] *
     [echo] * Updating keydef.xml file...
     [echo] *
     [copy] Copying 1 file to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741
     [echo] *
     [echo] * Done with dc-adjust-copy-to.
     [echo] *

chunk-check:

chunk:
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\fullditatopic.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\fullditamap.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\fullditamapandtopic.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\chunkedditamap.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\chunkedtopic.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\resourceonly.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\copytosource.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl
[job-helper] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\.job.xml t
o C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\copytotarget2sourcemap.list
[job-helper] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\job-helper.xsl

maplink-check:

maplink:
  [maplink] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\hierarchy.d
itamap to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\maplinks.unordered
  [maplink] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\preprocess\maplink.xsl

move-links-check:

move-links:
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\t
oolbox.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\o
il.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\taki
nggarbage.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\spra
ypainting.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\w
wfluid.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\w
heelbarrow.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\shov
ellingsnow.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\w
aterhose.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\g
arageconceptsoverview.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\p
aint.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\l
awnmower.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\orga
nizing.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\chan
gingtheoil.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\wash
ingthecar.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\t
ools.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\gara
getaskoverview.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\s
helving.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\w
orkbench.xml
[move-links] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\s
nowshovel.xml

topicpull-check:

topicpull:
[topicpull] Transforming into C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\ga
rageconceptsoverview.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concep
ts\garageconceptsoverview.xml.pull
[topicpull] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\xsl\preprocess\topicpull.xsl
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\la
wnmower.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\lawnmower.
xml.pull
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\oi
l.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\oil.xml.pull
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\pa
int.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\paint.xml.pull

[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\sh
elving.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\shelving.xm
l.pull
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\sn
owshovel.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\snowshove
l.xml.pull
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\to
olbox.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\toolbox.xml.
pull
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\to
ols.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\tools.xml.pull

[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\wa
terhose.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\waterhose.
xml.pull
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\wh
eelbarrow.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\wheelbar
row.xml.pull
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\wo
rkbench.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\workbench.
xml.pull
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\ww
fluid.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\concepts\wwfluid.xml.
pull
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\chang
ingtheoil.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\changingthe
oil.xml.pull
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\garag
etaskoverview.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\garaget
askoverview.xml.pull
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\organ
izing.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\organizing.xml.
pull
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\shove
llingsnow.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\shovellings
now.xml.pull
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\spray
painting.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\spraypaintin
g.xml.pull
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\takin
ggarbage.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\takinggarbag
e.xml.pull
[topicpull] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\washi
ngthecar.xml to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\tasks\washingtheca
r.xml.pull
     [move] Moving 19 files to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741

flag-module-check:

flag-module:

dc-preprocess:

dita.map.epub.init:
     [echo] +++ epub-specific properties:
     [echo] #Ant properties
     [echo] #Wed Jun 24 19:26:55 BST 2015
     [echo] css.output.dir=
     [echo] epub.dir=C\:\\ProgFiles\\XDocs40DRC3Server64\\Server\\publish\\DITA-OT185\\plugins\\org.dita4publishers.epub

     [echo] epub.hide.parent.link=yes
     [echo] epub.pubid.uri.stub=http\://my-URI-stub/
     [echo] epub.temp.dir=C\:\\ProgFiles\\XDocs40DRC3Server64\\Server\\publish\\DITA-OT185\\temp\\temp20150624192633741\
\epub_temp
     [echo] out.ext=.html
     [echo] preprocess.coderef.skip=true
     [echo] preprocess.conref.skip=true
     [echo] preprocess.conrefpush.skip=true
     [echo] preprocess.copy-flag.skip=true
     [echo] preprocess.copy-html.skip=true
     [echo] preprocess.copy-subsidiary.skip=true
     [echo] preprocess.flagging.skip=true
     [echo] preprocess.keyref.skip=true

epub-copy-css:
     [echo] Copying css files to 'C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\
epub_temp/
    [mkdir] Created dir: C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\epub_temp


epub-copy-css-system:
     [echo] copying system [${system.copycss.no}]
     [copy] Copying 2 files to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\epu
b_temp

epub-copy-css-user:

epub-copy-css-kindle:

dita.map.epub:
     [echo] [DEBUG] input file='C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\hi
erarchy.ditamap'
     [xslt] Transforming into C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741
     [xslt] Processing C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\hierarchy.d
itamap to C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\temp\temp20150624192633741\hierarchy.html
     [xslt] Loading stylesheet C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\plugins\org.dita4publishers.ep
ub\xsl\map2epub.xsl
     [xslt] Failed to process null

BUILD FAILED
C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\build.xml:44: The following error occurred while executing th
is line:
C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\plugins\org.dita4publishers.epub\build_transtype-epub.xml:171
: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.tools.ant.types.XMLCatalog$ExternalResolver.resolve(XMLCatalog.java:1076)
        at org.apache.tools.ant.types.XMLCatalog.resolve(XMLCatalog.java:425)
        at net.sf.saxon.style.XSLGeneralIncorporate.getIncludedStylesheet(XSLGeneralIncorporate.java:104)
        at net.sf.saxon.style.XSLStylesheet.spliceIncludes(XSLStylesheet.java:754)
        at net.sf.saxon.style.XSLGeneralIncorporate.getIncludedStylesheet(XSLGeneralIncorporate.java:168)
        at net.sf.saxon.style.XSLStylesheet.spliceIncludes(XSLStylesheet.java:754)
        at net.sf.saxon.style.XSLStylesheet.preprocess(XSLStylesheet.java:676)
        at net.sf.saxon.PreparedStylesheet.setStylesheetDocument(PreparedStylesheet.java:331)
        at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:163)
        at net.sf.saxon.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:139)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:300)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.createTransformer(TraXLiaison.java:317)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:178)
        at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:819)
        at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:407)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:392)
        at org.apache.tools.ant.Target.performTasks(Target.java:413)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:392)
        at org.apache.tools.ant.Target.performTasks(Target.java:413)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.Main.runBuild(Main.java:811)
        at org.apache.tools.ant.Main.startAnt(Main.java:217)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: javax.xml.transform.TransformerException: Malformed URL plugin:org.dita4publishers.common.xslt:xsl/reportPara
metersBase.xsl(base file:/C:/ProgFiles/XDocs40DRC3Server64/Server/publish/DITA-OT185/plugins/org.dita4publishers.epub/xs
l/map2epubImpl.xsl)
        at org.apache.xml.resolver.tools.CatalogResolver.resolve(Unknown Source)
        ... 47 more
Caused by: java.net.MalformedURLException: unknown protocol: plugin
        at java.net.URL.<init>(URL.java:574)
        at java.net.URL.<init>(URL.java:464)
        ... 48 more

Total time: 23 seconds

**Comment by drmacro** [comment]
Can you check that the plugin:

org.dita4publishers.common.xslt

Is installed? Did you use the full D4P RC14 plugins zip or just the epub-only zip?

You will get this malformed URL failure if the thing that should be at the end of the URL isn't actually there--it's not that the URL is really malformed, it's that the base URL handler gets the URL because the catalog resolver didn't resolve it and the base URL handler doesn't know what to do with a "plugin:" URN. But the real failure is that the URN can't be resolved because something isn't there.

**Comment by brbk** [comment]
Thanks for the response. 

org.dita4publishers.common.xslt was there. However, I downloaded it again, ran it again, and now epub "failed to compile stylesheet" (copied below)

In the .org user guide, it says, "The doctypes plugin is the only plugin that is required in order to work with DITA for Publishers content. The other plugins may be used or not as you choose." 

so I installed .epub and .doctypes, but then I downloaded and installed 5 more plugins according to messages about other missing plugins, and then got stuck on the malformed url.

Failing here now,

BUILD FAILED
C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\build.xml:44: The following error occurred while executing th
is line:
C:\ProgFiles\XDocs40DRC3Server64\Server\publish\DITA-OT185\plugins\org.dita4publishers.epub\build_transtype-epub.xml:171
: javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 1 error detected.
        at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:176)
        at net.sf.saxon.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:139)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:300)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.createTransformer(TraXLiaison.java:317)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:178)
        at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:819)
        at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:407)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:392)
        at org.apache.tools.ant.Target.performTasks(Target.java:413)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:392)
        at org.apache.tools.ant.Target.performTasks(Target.java:413)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.Main.runBuild(Main.java:811)
        at org.apache.tools.ant.Main.startAnt(Main.java:217)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 29 seconds

**Comment by drmacro** [comment]
I think you're taking that part of the User Guide a little too literally. If you want to produce EPUB you need to install at least all the plugins that are in the EPUB-only toolkit plugin Zip file. Safer to install the full D4P toolkit plugin package.

**Comment by brbk** [comment]
I did install "all the plugins that are in the EPUB-only toolkit plugin Zip file".

**Comment by drmacro** [comment]
OK, I'm testing things under Windows now.

**Comment by drmacro** [comment]
It looks like there is a problem with RC14 EPUB zip. If can, please install the plugins from the full D4P RC14 package--that should resolve the problem if it is just missing plugins.

**Comment by drmacro** [comment]
The problem I'm seeing with the RC14 plugin package is that it includes the HTML2 plugin, which in turn requires a plugin that's not there. This causes integration to fail.

When I remove the HTML2 plugin and rerun the integrator, that succeeds as expected.

I am then able to produce an EPUB using this command line:

````
tools\ant\bin\ant -Dtranstype=epub -Dargs.input=samples\hierarchy.ditamap -l epub.log
````

So while there is an issue with the EPUB zip package, you did not report that issue, which suggests that there's some configuration problem in your local toolkit.

I started with a clean install of the 1.8.5 OT, unpacked the EPUB plugin zip, copied the plugins to the OT plugins/ directory, removed the HTML2 plugin, ran integrator.xml, and then attempted to generate an EPUB.

I will correct the EPUB zip package and replace the one that's on GitHub

**Comment by brbk** [comment]
Thank you. I will try exactly as above.

**Comment by drmacro** [comment]
OK, I've corrected the EPUB plugin zip for the RC14 release and updated the release on GitHub.

My packaging script was using the wrong logic. 

I tested on windows by unpacking the new zip, installing into a clean 1.8.5 OT, and verifying that the EPUB transform worked.
