### ISSUE TITLE
DITA OT 2.2.2 Duplicated project name

### ISSUE THREAD

**Issue by speich** [dita4publishers/dita4publishers#23]
When trying to use d4p with ot 2.2.2 I get the following errors: 

Buildfile: dita-ot-2.2.2\build.xml Duplicated project name in import. Project dita2html5 defined first in dita-ot-2.2.2\plugins\org.dita.html5\build_dita2html5.xml and again in dita-ot-2.2.2\plugins\org.dita4publishers.html5\build_transtype-html5.xml

BUILD FAILED
Target "move-links" does not exist in the project "DOST". It is used from target "dc-preprocess".

Are there any plans to make it work with OT 2 ?

**Comment by drmacro** [comment]
I do not currently support the 2.x OT. I will be working on adding support in April. At least the EPUB transform on the develop branch should work with 2.1.2  but I haven't tested it with 2.2.2 or 2.2.3.

2.2.3 will be my target version as 2.2.3 fixes a serious implementation error in the support for branch filtering (2.2.2 applies key scope prefixes and suffixes incorrectly to descendant key scopes).

**Comment by drmacro** [comment]
2.4 is now the lowest target version.

This error does not occur in my testing. Closing as fixed/not-a-bug
