### ISSUE TITLE
Insertion of aria-labelledby element in EPUB XHTML (DITA-OT 2.4.x)

### ISSUE THREAD

**Issue by Hasimir** [dita4publishers/dita4publishers#24]
As discussed on dita-users, the current develop branch of the EPUB 3 builds running with DITA-OT 2.4 and tested with both 2.4.0 and 2.4.1 inserts the following element in almost all EPUB XHTML files:

	<article role="article" aria-labelledby="ariaid-title1">

The resulting EPUBs then produce "Referenced resource could not be found in the EPUB" errors for each of those files.

The article element is only inserted for XHTML files generated from DITA topic files, so it does not appear in files like nav.xhtml.

The @aria-labelledby attribute is lurking in the OT's org.dita.html5 plugin and requires filtering it out during the EPUB cleanup.

**Comment by drmacro** [comment]
Fix was to generate the required ID on the generated element for the title. With that change, epubcheck passes.

Fix committed on ot-version/2.x branch.
