### ISSUE TITLE
EPUB UTC time conversion half-fixed

### ISSUE THREAD

**Issue by Hasimir** [dita4publishers/dita4publishers#25]
As mentioned on dita-users the previous fix to convert localtime to UTC is an odd half-fix.  Specifically the time conversion does correctly calculate the difference between the system time which the OT runs on and UTC, including adjusting the date where necessary.  However the time is only ever recorded as a 12 hour clock and not a 24 hour clock.  So any UTC time between 13:00Z and 23:59Z loses 12 hours.

I am not certain what happens with 00:00Z since I haven't run a transformation at exactly that time.  I'm also not certain if this is an issue with XSLT or Java itself.  It is, however, less of a worry than the situation prior to the half-fix since it does at least prevent the generation of a timestamp in the future from the point of the transformation which was previously the case for those of us ahead of UTC (i.e. from Europe to Asia and Oceania).  It is also not picked up by epubcheck.

**Comment by drmacro** [comment]
This is an EPUB issue that is a continuation of the existing issue. closing this issue and reopening the epub issue.

**Comment by drmacro** [comment]
The bug appeared to be using "h" rather than "H" for the hour field. In my testing using a simple test XSLT the 24-hour time correctly reflects the time. I tested by setting my timezone to Australia time at 11:54 pm. The resulting UTC time correctly reflects the previous day and the correct hour of the day.

**Comment by drmacro** [comment]
I have committed an update on the develop and ot-version/2.x branches. Will provide a build zip for testing.
