### ISSUE TITLE
Localize strings in common enumeration code, elsewhere

### ISSUE THREAD

**Issue by drmacro** [dita4publishers/dita4publishers#6]
From Ben Welman:

The hard code text I meant is
"Part", "Chapter" and "Appendix"(in commonHtmlBookmapEnumeration.xsl and commonHtmlEnumeration.xsl. These string names are NOT in the normal HTML localization, strange.
"Figure" and "Table" in commonHtmlEnumeration.xsl. These string names are in the normal HTML localization.

**Comment by blefort** [comment]
Fixed in https://github.com/dita4publishers/org.dita4publishers.common.html/commit/4f81727eba3f52548858963e8d307e48120ee316
