### ISSUE TITLE
Travis-CI: test does not work on version 1.7.5

### ISSUE THREAD

**Issue by blefort** [dita4publishers/dita4publishers#8]
I am trying to implements Travis-CI for the project, since we have to test it on at least 3 versions of the OT, plus multiple transforms.

The current test (a simple map build) works on the version 1.8.5 of the OT but failed on 1.7.5.

https://travis-ci.org/dita4publishers/dita4publishers

The error is:
```bash
BUILD FAILED
/home/travis/build/dita4publishers/dita4publishers/DITA-OT1.7.5/test/ant/sample_d4p-html5.xml:11: The following error occurred while executing this line:
/home/travis/build/dita4publishers/dita4publishers/DITA-OT1.7.5/build.xml:44: The following error occurred while executing this line:
/home/travis/build/dita4publishers/dita4publishers/DITA-OT1.7.5/plugins/org.dita-community.adjust-copy-to/adjust-copy-to-preprocess.xml:106: Problem: failed to create task or type job-helper
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
```

It might be due to the version of ant on Travis, but I am not sure. It is working on the version 1.8.5.

**Comment by drmacro** [comment]
See my comment on the adjust-copy-to-issue: I don't intend to support 1.7 unless there's some compelling reason to do so.

**Comment by drmacro** [comment]
Updated the travis test scripts to not try to run 1.6 or 1.7 as they are not supported now.

**Comment by drmacro** [comment]
Need to support 1.7.5 as Oracle (and probably others) are using 1.7.5 and won't be able to upgrade quickly. Restoring 1.7.5 test case.

**Comment by brbk** [comment]
Where is this at with DITA OT version support? I am trying to implement EPub with 1.7.5 and the build is failing at adjust-copy-to-preprocess.xml:106: Problem: failed to create task or type job-helper

**Comment by drmacro** [comment]
I have started work on a way to support all OT versions in the dc-preprocessing-extensions plugin but I probably won't be able to work on it more until this weekend at the earliest due to other priorities.

**Comment by brbk** [comment]
Ok. Thx
